### ISSUE TITLE
Determine master process

### ISSUE THREAD

**Issue by eportico** [meteorhacks/cluster#29] opened 2015-03-15 13:43 UTC
how can I know which is the master process to perform actions that should only be performed once ?
thx

**Comment by arunoda** [comment] 2015-03-15 14:18
There is no specific way to define a master and that's not our goal. Everyone can be a master. The one you send traffic is the master.

**Comment by eportico** [comment] 2015-03-15 19:12
I need to perform actions MapReduce periodically for metrics collection aggregation, but I need this to make it a single process, not all processes in the cluster. ¿? I need identify a process cluster in the code

**Comment by dropfen** [comment] 2015-03-15 20:19
The best would be, to create a separate App which only do this. and run it on a other port.

@arunoda, we need a pattern for this problem in the README.
Actually I’m not sure if this is really cluster related, I guess this is a meteor architecture *feature*.
But you see this behavior with cluster, when you have a multicore dev-env ;)

**Comment by rhyslbw** [comment] 2015-03-15 23:24
@dropfen Doesn't setting the separated service to not use the multicore cluster option allow for this configuration?

**Comment by dropfen** [comment] 2015-03-15 23:34
@rhyslbw <https://github.com/rhyslbw> Sorry, I didn’t got the question. Can you please explain what you mean?

**Comment by rhyslbw** [comment] 2015-03-16 02:10
You have to configure multicore support in each cluster service by exporting CLUSTER_WORKERS_COUNT right? So for the app that needs to just be a single process, doesn't removing this env var solve the issue?

**Comment by dropfen** [comment] 2015-03-16 02:24
sure, but if you are running a single instance you don't want have there cluster at all. As I understood, the issue is, that @eportico is running a periodical job on the server side only. and cluster was made to primary scale the front-end data flow.

**Comment by dropfen** [comment] 2015-03-16 02:25
guys, please correct me, if I'm wrong

**Comment by arunoda** [comment] 2015-03-16 02:30
I think all of you are correct :) 

I hope this map reduce task is pretty small and won't take much resources. So, it's okay to run a seperate app even if you are running a single core machine. 

We can make this simple with containers. Cluster will have coreos support very soon.(well basically, etcd support) then there will be a lesson on BulletProof Meteor on CoreOS. 

After that, we could achieve these kind a things very easily.

**Comment by rhyslbw** [comment] 2015-03-16 02:56
@dropfen You would still be better off using Cluster to manage the service discovery to keep absolute urls out of your codebase

**Comment by arunoda** [comment] 2015-03-16 03:01
Yeah. That's true.
But if this is just a process with no DDP stuff, it's just fine without
running cluster.

**Comment by eportico** [comment] 2015-03-16 07:40
Hi guys,
my solution for identify a process 'master' is : 
if(process.env['CLUSTER_WORKER_ID']) return;

**Comment by arunoda** [comment] 2015-03-16 07:50
Okay, this the controller process in a multi core box.
Yes, you can think it as a master, if you are running only a single server.

**Comment by arunoda** [comment] 2015-03-16 10:44
Guys, hope we can close this now.

**Closed by arunoda** 2015-03-16 10:44 UTC

**Comment by Kostanos** [comment] 2016-09-28 13:31
I have the same issue, it is not only mapReduce, you may have a lot of staff that should be run once, like: fixtures generator, data migration, default data generator etc.. making separate app for this staff will add extra expenses on infrastructure and deploy process.

There should be a way to identify a unique instance, to run some code only once

**Comment by gduquesnay** [comment] 2016-11-17 14:45
We are trying to use CLUSTER_WORKER_ID == 1 for this.  I'm worried because @arunoda hasn't mentioned that anywhere.  Is there some reason that I'm missing why this won't work?  Note we are on a single server with multiple cores at the moment.  I get that this will not work for multiple servers.
